<a href="https://colab.research.google.com/github/YashasaveeKesarwani99/Exploratory-data-analysis/blob/main/L1L2regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

Saving MELBOURNE_HOUSE_PRICES_LESS.csv to MELBOURNE_HOUSE_PRICES_LESS (1).csv

In [15]:

import io

data = pd.read_csv(io.BytesIO(uploaded['MELBOURNE_HOUSE_PRICES_LESS.csv']))
data.head()

         Suburb           Address  ...  Distance                 CouncilArea
0    Abbotsford     49 Lithgow St  ...       3.0          Yarra City Council
1    Abbotsford     59A Turner St  ...       3.0          Yarra City Council
2    Abbotsford     119B Yarra St  ...       3.0          Yarra City Council
3    Aberfeldie        68 Vida St  ...       7.5  Moonee Valley City Council
4  Airport West  92 Clydesdale Rd  ...      10.4  Moonee Valley City Council

[5 rows x 13 columns]

In [16]:
data.shape
data = data.drop(['Address'], axis=1)
data.columns
data.isna().sum()

Suburb               0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [17]:
# cleaning our data
data['Price'] = data['Price'].fillna(data.Price.mean())

data.isna().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Postcode         0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
dtype: int64

In [18]:
# handling categorical data
data = pd.get_dummies(data, drop_first=True)
data.head()

   Rooms  ...  CouncilArea_Yarra Ranges Shire Council
0      3  ...                                       0
1      3  ...                                       0
2      3  ...                                       0
3      3  ...                                       0
4      2  ...                                       0

[5 rows x 1020 columns]

In [19]:
# preparing train test split

X = data.drop('Price', axis=1)
Y = data['Price']

from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(X,Y,test_size = 0.3, random_state = 2)

In [22]:
# applying regular linear regression model

from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_x,train_y)

reg.score(test_x,test_y)

-590370780329.0167

In [24]:
# regularizing through lasso

from sklearn import linear_model

lasso_reg = linear_model.Lasso(alpha=50,max_iter=100,tol=.1)

lasso_reg.fit(train_x,train_y)

lasso_reg.score(test_x,test_y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3096027098109251.5, tolerance: 1164891847869254.0
  positive)

0.46269048723247286

In [25]:
# regularizing through Ridge

from sklearn import linear_model

Ridge_reg = linear_model.Ridge(alpha=50,max_iter=100,tol=.1)

Ridge_reg.fit(train_x,train_y)

Ridge_reg.score(test_x,test_y)

0.4605166456181958

In [ ]:
# the L1 and L2 regularization significantly increased the prediction and decreased the overfitting of model

This module describes the concept of regularization in Linear regression through L1 and L2 regression.